spring:
  application:
    name: news-stock

  datasource:
    url: jdbc:mariadb://localhost:3305/newstock
    username: root
    password: system

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE

  jwt:
    secret: flkselkfdlkdfjeoifiowjdkjnlflnsenlflnekfkjr

api:
  base:
    url: https://openapi.naver.com/v1/search/news.json
  query:
    sort: date
    display: 20

naver:
  client:
    id: xPUQv5Cn2RH7awxJc1re
    secret: JQjpJochy7

feign:
  client:
    config:
      default:
        loggerLevel: FULL