spring:
  application:
    name: news-stock

  datasource:
    url: jdbc:mariadb://localhost:3305/newstock
    username: root
    password: system

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE

  jwt:
    secret: flkselkfdlkdfjeoifiowjdkjnlflnsenlflnekfkjr